FROM oraclelinux:8

RUN dnf -y update

# Start Node.JS for Oracle Linux: https://yum.oracle.com/oracle-linux-nodejs.html
RUN dnf -y module enable nodejs:18 && \
    dnf -y install nodejs npm && \
    rm -rf /var/cache/dnf
# End Node.JS for Oracle Linux: https://yum.oracle.com/oracle-linux-nodejs.html

WORKDIR /usr/src/app/backend

COPY package*.json ./

RUN npm install

EXPOSE 4000

CMD ["npm", "run", "dev"]
